// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/withinfewweeks-shell/Current.tsx": () => import("../components/mockups/withinfewweeks-shell/Current.tsx"),
  "./components/mockups/withinfewweeks-shell/Warm.tsx": () => import("../components/mockups/withinfewweeks-shell/Warm.tsx")
};
